# Generated by Django 4.2.10 on 2025-04-29 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_obligations', '0003_alter_bankobligation_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_payable', '0002_supplier_pdf_file_alter_accountpayable_status'),
        ('accounts_receivable', '0002_bank_pdf_file_client_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='event title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('event_type', models.CharField(choices=[('receivable', 'Account Receivable'), ('payable', 'Account Payable'), ('obligation', 'Bank Obligation'), ('reminder', 'Payment Reminder'), ('custom', 'Custom Event')], max_length=20, verbose_name='event type')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('all_day', models.BooleanField(default=True, verbose_name='all day event')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, verbose_name='Google Calendar ID')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='Google Event ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='bank_obligations.bankobligation')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts_payable.accountpayable')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts_receivable.accountreceivable')),
            ],
            options={
                'verbose_name': 'calendar event',
                'verbose_name_plural': 'calendar events',
                'ordering': ['start_date'],
            },
        ),
    ]
