# Generated by Django 5.2 on 2025-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='banks/pdf/', verbose_name='PDF file'),
        ),
        migrations.AddField(
            model_name='client',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='clients/pdf/', verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('treasury', 'Treasury'), ('with_representative', 'With Representative'), ('in_collection', 'In Collection'), ('treasury_rejected', 'Treasury Rejected'), ('collected', 'Collected'), ('client_rejected', 'Client Rejected')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
