# Generated by Django 5.2 on 2025-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_payable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/pdf/', verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='status',
            field=models.CharField(choices=[('covered', 'Covered'), ('under_coverage', 'Under Coverage'), ('delivered', 'Delivered'), ('covered_and_delivered', 'Covered and Delivered'), ('under_coverage_and_delivered', 'Under Coverage and Delivered'), ('disbursed', 'Disbursed'), ('covered_and_disbursed', 'Covered and Disbursed'), ('under_coverage_and_disbursed', 'Under Coverage and Disbursed'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='covered', max_length=40, verbose_name='status'),
        ),
    ]
