# Generated by Django 4.2.10 on 2025-04-05 12:23

import cash_transactions.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='account name')),
                ('arabic_name', models.CharField(max_length=100, verbose_name='account name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='initial balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cash account',
                'verbose_name_plural': 'cash accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('arabic_name', models.CharField(max_length=100, verbose_name='category name (Arabic)')),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='category type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cash_transactions.transactioncategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'transaction category',
                'verbose_name_plural': 'transaction categories',
                'ordering': ['category_type', 'name'],
                'unique_together': {('name', 'category_type', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='transaction date')),
                ('reference_number', models.CharField(default=cash_transactions.models.CashTransaction.generate_reference_number, editable=False, max_length=20, unique=True, verbose_name='reference number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='receipt image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cash_transactions.transactioncategory', verbose_name='category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='cash_transactions.cashtransaction', verbose_name='related transaction')),
            ],
            options={
                'verbose_name': 'cash transaction',
                'verbose_name_plural': 'cash transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='cash_transactions.cashaccount', verbose_name='cash account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='cash_transactions.cashtransaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'cash account transaction',
                'verbose_name_plural': 'cash account transactions',
                'ordering': ['-created_at'],
                'unique_together': {('account', 'transaction')},
            },
        ),
    ]
