# Generated by Django 4.2.10 on 2025-04-05 12:23

import bank_obligations.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_receivable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('loan', 'Loan'), ('credit_line', 'Credit Line'), ('letter_of_credit', 'Letter of Credit')], max_length=20, verbose_name='obligation type')),
                ('obligation_number', models.CharField(default=bank_obligations.models.BankObligation.generate_obligation_number, editable=False, max_length=20, unique=True, verbose_name='obligation number')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='branch')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='account number')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='principal amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='interest rate (%)')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually'), ('lump_sum', 'Lump Sum')], default='monthly', max_length=20, verbose_name='payment frequency')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='payment amount')),
                ('total_payments', models.PositiveIntegerField(default=1, verbose_name='total number of payments')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('purpose', models.TextField(blank=True, verbose_name='purpose')),
                ('collateral', models.TextField(blank=True, verbose_name='collateral')),
                ('guarantors', models.TextField(blank=True, verbose_name='guarantors')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='accounts_receivable.bank', verbose_name='bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank obligation',
                'verbose_name_plural': 'bank obligations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ObligationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='principal portion')),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='interest portion')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='reference number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_payments', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bank_obligations.bankobligation', verbose_name='obligation')),
            ],
            options={
                'verbose_name': 'obligation payment',
                'verbose_name_plural': 'obligation payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
