# Generated by Django 4.2.10 on 2025-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_obligations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankobligation',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('covered_with_papers', 'Covered with Papers'), ('covered_with_cash', 'Covered with Cash'), ('paid', 'Paid')], default='created', max_length=30, verbose_name='status'),
        ),
    ]
