# Generated by Django 4.2.10 on 2025-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_obligations', '0002_bankobligation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankobligation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='bankobligation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
